SELECT * FROM `awesome chocolates`.cleaned_data;

rename table cleaned_data to customers;

select * from customers
where age>50;

#1.Revenue generated by male and female customers ?

select gender, sum(purchase_amount) as revenue from customers
group by gender;

#2.Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount from customers
where discount_applied = 'YES' and purchase_amount >= (select avg(purchase_amount)from customers);

#3.Which are the top 5 products with highest average review rating ?
select item_purchased, Round(avg(review_rating),2) as 'Average product Ranking' from customers
group by item_purchased
order by avg(review_rating) desc 
limit 5 ;

#4.Compare the average purchase amount between standard and Express Shipping ?
select shipping_type, round(avg(purchase_amount),2)as 'Shipping Amount' from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

#5.Which 5 products have the highest percentages of purchases with discount applied ?
select subscription_status, count(customer_id) as 'Total Customers',
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by avg_spend,total_revenue desc;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS 'discount_rate'
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


#Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue desc;